### PR TITLE
support for multiple webgeom quick starters

### PR DESCRIPTION
**Pull request by jread-usgs**
HUC8, Level III ecoregions, states.
Finishes up #88

### CODE REVIEW

**Comment by jread-usgs** [comment]
@lawinslow and @ldecicco-USGS , I would like to be able to do this for "NWIS::site1,site2" for those supported in the `hydrofabric` WFS...but maybe that is a bit out of scope (and too domain specific) for this package.

**Comment by lawinslow** [comment]
Would it be the point or watershed? I think there's no reason you couldn't depend on the hydrofabric package and use it to access those types of geo data. Clearly, not there yet, but could be soon.

**Comment by jread-usgs** [comment]
Was assuming it would be the watershed, but there is value in getting the point too (which would be much easier w/ dataRet)

**Comment by lawinslow** [comment]
What's the interface that would be needed from hydrofabric? 

```R
get_shp_watershed(nwis_id)
get_wfs_watershed(nwis_id)
````
Something like that?

**Comment by jread-usgs** [comment]
well, this could actually go directly to the WFS hosted by sciencebase, so it may not need to import hydrofrabic, but would be using some of the same resources? maybe this is a bad idea. See the pattern here? https://github.com/USGS-R/geoknife/blob/master/R/02-webgeom-obj.R#L126

The same would also apply to SB hosted, but the namespace is different and the `wfs(webgeom)` would need to be set to that WFS, instead of default CIDA.

**Comment by lawinslow** [comment]
If you built it in there, I'd use it. We'll have to figure out how that WFS will work on SB and if its ID would change with updates or not (might affect how you decide to link to the service). 

You'll have to decide if you use the points, watersheds, or both. If both, can you differentiate? "NWIS_WS: site1, site2" vs "NWIS: site1, site2" maybe

**Comment by jread-usgs** [comment]
Cool. would be very powerful to link this w/ hydrofabric, dataRet, and geoknife in a sci workflow.

**Comment by lawinslow** [comment]
Let's plan on revisiting this when we get that stuff up for hydrofabric

**Comment by jread-usgs** [comment]
sounds good.

**Pull request merged**
