### PR TITLE
changes that should allow the OUTPUT_TYPE to get set to application/z…

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
…ip, currently works against the default (netCDF) format

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
eek, not sure why the tests failed...

As I showed you, using the demo file the OUTPUT_TYPE seams to be getting set but then it's not passed through to the xml creation stuff.

**Comment by jread-usgs** [comment]
hmm...this passed local tests for you @dblodgett-usgs ? https://ci.appveyor.com/project/jread-usgs/geoknife/build/0.2.2.233#L257

**Comment by jread-usgs** [comment]
let me take a shot at figuring out that error.

**Comment by dblodgett-usgs** [comment]
Prior to making the changes here, tests passed. That was just making sure that the changes on the production processing service didn't break existing functionality.

**Comment by jread-usgs** [comment]
Ok, I didn't understand that the first time. Makes sense. I am re-opening this, as it would be good to riff on the changes and take care of it on this PR.

**Comment by jread-usgs** [comment]
I think the main issue is checking `!is.character(.Object@processInputs$OUTPUT_TYPE)` instead of `!is.null(.Object@processInputs$OUTPUT_TYPE)`

**Comment by jread-usgs** [comment]
weirder issue is that `geoknife` is flipping the knife from a subset to a summary...this is odd

**Comment by jread-usgs** [comment]
nevermind my last comment, that was not happening. I was just reading it incorrectly.

**Comment by jread-usgs** [comment]
part of the issue is here: #208

**Comment by jread-usgs** [comment]
pretty cool, now you can use the `subset` to return a zipped folder of geotiffs for each time stamp

image

```R
library(geoknife)

fabric <- webdata(url = 'http://cida.usgs.gov/thredds/dodsC/prism')
fabric
query(fabric, 'variables')
variables(fabric) <- 'ppt'

query(fabric, 'times')
times(fabric) <- as.POSIXct(c("1985-01-01","1992-01-01"))

# use ALL variables
variables(fabric) <- query(fabric, 'variables')

stencil <- simplegeom(data.frame('point1'=c(-89, 46), 'point2'=c(-78.6, 42.2)))

knife = webprocess(algorithm = list('OPeNDAP Subset'="gov.usgs.cida.gdp.wps.algorithm.FeatureCoverageOPeNDAPIntersectionAlgorithm"))
job <- geoknife(stencil,fabric, knife, wait = TRUE, OUTPUT_TYPE="geotiff")
file <- download(job, destination = '../prism_data.zip')
```

**Comment by jiwalker-usgs** [comment]
:sunglasses:

**Comment by jread-usgs** [comment]
:+1:

**Pull request merged**
