### PR TITLE
CRS update

### PR DESCRIPTION
**Pull request by dblodgett-usgs**

### CODE REVIEW

**Comment by jread-usgs** [comment]
Works for me. Nice :+1:

**Comment by dblodgett-usgs** [comment]
Cool - I'm getting all the dev deps updated locally and will double check an `R CMD CHECK --as-cran --run-donttest` Want to make me a maintainer on this repo so I can cut a release or do you want to?

**Comment by dblodgett-usgs** [comment]
@wdwatkins Can you cut a release and submit this to CRAN? 
[geoknife_1.6.4.tar.gz](https://github.com/USGS-R/geoknife/files/4651451/geoknife_1.6.4.tar.gz)

**Comment by wdwatkins** [comment]
Yes, although I am not a package maintainer either, so @jread-usgs you will still have to do the email confirmation

**Comment by jread-usgs** [comment]
can do and will do when it comes in

**Pull request merged**
