### PR TITLE
rebuild readme

### PR DESCRIPTION
**Pull request by wdwatkins**
@lindsayplatt is tweeting about this, so wanted to get the version updated in the readme title.  Maybe ideally the readme build could be baked into the package build command?  I'm rusty on package build stuff.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Huh -- I've got no idea. Didn't realize the readme was autogenerated. Take a look at the rendered version -- there are some issues with headers not showing up right.

**Comment by dblodgett-usgs** [comment]
@wdwatkins -- was just coming back to geoknife and seeing this PR never got merged. Can you take another look? I've got a few changes incoming that shouldn't really affect this. But it would be good to get this off the plate.

**Comment by wdwatkins** [comment]
Yeah, sorry about that.  Looks like all the #s were escaped for some reason, hence the titles not rendering

**Comment by wdwatkins** [comment]
@dblodgett-usgs  Should be good to go now.  There must have been some Rmarkdown updates that changed heading rendering since this was first written.

**Pull request merged**
