### PR TITLE
Partial for #189

### PR DESCRIPTION
**Pull request by jread-usgs**
try:
```R
datagroup <- query('webdata')
datagroup
datagroup[1:3]
datagroup[[1]]
webdata(datagroup[7])
```

missing the rest of the metadata, but has a new class for the collection of datasets and some methods (`[` and `[[`) for accessing and print/show

### CODE REVIEW

**Comment by jread-usgs** [comment]
@aappling-usgs I think this has a good bit of what you asked for, although it is missing the additional metadata piece.

**Comment by aappling-usgs** [comment]
yep, looks pretty nice. might want to add some spaces before 'url: " so that it's easier to visually separate the items. 

i tried this:
```r
wd <- query('webdata')
wd[[5]]
```
and was a little surprised to find that the dataset name had disappeared. it's not a big deal -- my next try was `wd[5]`, which worked fine - but you might consider including the name within each named element or adding it in when the user selects 1+ elements from the list with [[]].

**Comment by jread-usgs** [comment]
cool, thanks for the feedback!

I added the spacing you requested, and now wd[[3]] strips the class and returns a sub list. Not quite sure if that is the desired behavior. 

Also added 
```R
wd <- query('webdata')
abstract(wd[14:15])
```
which returns the abstract text for the dataset(s). I don't have a `title` or `url` methods, but those would make sense if this patterns fits.

**Comment by aappling-usgs** [comment]
`abstract(...)` fits well with your style in this package. i like it. `title()` and `url()` would also be good.

**Pull request merged**
